/*
 * Generated by gdbus-codegen 2.32.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "nautilus-generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface apps.Nautilus.FileOperations
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:NautilusDBusFileOperations
 * @title: NautilusDBusFileOperations
 * @short_description: Generated C code for the apps.Nautilus.FileOperations D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-apps-Nautilus-FileOperations.top_of_page">apps.Nautilus.FileOperations</link> D-Bus interface in C.
 */

/* ---- Introspection data for apps.Nautilus.FileOperations ---- */

static const _ExtendedGDBusArgInfo _nautilus_dbus_file_operations_method_info_copy_uris_IN_ARG_SourceFilesURIList =
{
  {
    -1,
    "SourceFilesURIList",
    "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nautilus_dbus_file_operations_method_info_copy_uris_IN_ARG_DestinationDirectoryURI =
{
  {
    -1,
    "DestinationDirectoryURI",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _nautilus_dbus_file_operations_method_info_copy_uris_IN_ARG_pointers[] =
{
  &_nautilus_dbus_file_operations_method_info_copy_uris_IN_ARG_SourceFilesURIList,
  &_nautilus_dbus_file_operations_method_info_copy_uris_IN_ARG_DestinationDirectoryURI,
  NULL
};

static const _ExtendedGDBusMethodInfo _nautilus_dbus_file_operations_method_info_copy_uris =
{
  {
    -1,
    "CopyURIs",
    (GDBusArgInfo **) &_nautilus_dbus_file_operations_method_info_copy_uris_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-copy-uris",
  FALSE
};

static const _ExtendedGDBusMethodInfo _nautilus_dbus_file_operations_method_info_empty_trash =
{
  {
    -1,
    "EmptyTrash",
    NULL,
    NULL,
    NULL
  },
  "handle-empty-trash",
  FALSE
};

static const _ExtendedGDBusArgInfo _nautilus_dbus_file_operations_method_info_copy_file_IN_ARG_SourceFileURI =
{
  {
    -1,
    "SourceFileURI",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nautilus_dbus_file_operations_method_info_copy_file_IN_ARG_SourceDisplayName =
{
  {
    -1,
    "SourceDisplayName",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nautilus_dbus_file_operations_method_info_copy_file_IN_ARG_DestinationDirectoryURI =
{
  {
    -1,
    "DestinationDirectoryURI",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _nautilus_dbus_file_operations_method_info_copy_file_IN_ARG_DestinationDisplayName =
{
  {
    -1,
    "DestinationDisplayName",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _nautilus_dbus_file_operations_method_info_copy_file_IN_ARG_pointers[] =
{
  &_nautilus_dbus_file_operations_method_info_copy_file_IN_ARG_SourceFileURI,
  &_nautilus_dbus_file_operations_method_info_copy_file_IN_ARG_SourceDisplayName,
  &_nautilus_dbus_file_operations_method_info_copy_file_IN_ARG_DestinationDirectoryURI,
  &_nautilus_dbus_file_operations_method_info_copy_file_IN_ARG_DestinationDisplayName,
  NULL
};

static const _ExtendedGDBusMethodInfo _nautilus_dbus_file_operations_method_info_copy_file =
{
  {
    -1,
    "CopyFile",
    (GDBusArgInfo **) &_nautilus_dbus_file_operations_method_info_copy_file_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-copy-file",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _nautilus_dbus_file_operations_method_info_pointers[] =
{
  &_nautilus_dbus_file_operations_method_info_copy_uris,
  &_nautilus_dbus_file_operations_method_info_empty_trash,
  &_nautilus_dbus_file_operations_method_info_copy_file,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _nautilus_dbus_file_operations_interface_info =
{
  {
    -1,
    "apps.Nautilus.FileOperations",
    (GDBusMethodInfo **) &_nautilus_dbus_file_operations_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "file-operations",
};


/**
 * nautilus_dbus_file_operations_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-apps-Nautilus-FileOperations.top_of_page">apps.Nautilus.FileOperations</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
nautilus_dbus_file_operations_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_nautilus_dbus_file_operations_interface_info;
}

/**
 * nautilus_dbus_file_operations_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #NautilusDBusFileOperations interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
nautilus_dbus_file_operations_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * NautilusDBusFileOperations:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-apps-Nautilus-FileOperations.top_of_page">apps.Nautilus.FileOperations</link>.
 */

/**
 * NautilusDBusFileOperationsIface:
 * @parent_iface: The parent interface.
 * @handle_copy_file: Handler for the #NautilusDBusFileOperations::handle-copy-file signal.
 * @handle_copy_uris: Handler for the #NautilusDBusFileOperations::handle-copy-uris signal.
 * @handle_empty_trash: Handler for the #NautilusDBusFileOperations::handle-empty-trash signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-apps-Nautilus-FileOperations.top_of_page">apps.Nautilus.FileOperations</link>.
 */

static void
nautilus_dbus_file_operations_default_init (NautilusDBusFileOperationsIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * NautilusDBusFileOperations::handle-copy-uris:
   * @object: A #NautilusDBusFileOperations.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_SourceFilesURIList: Argument passed by remote caller.
   * @arg_DestinationDirectoryURI: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-apps-Nautilus-FileOperations.CopyURIs">CopyURIs()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nautilus_dbus_file_operations_complete_copy_uris() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-copy-uris",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NautilusDBusFileOperationsIface, handle_copy_uris),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRV, G_TYPE_STRING);

  /**
   * NautilusDBusFileOperations::handle-empty-trash:
   * @object: A #NautilusDBusFileOperations.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-apps-Nautilus-FileOperations.EmptyTrash">EmptyTrash()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nautilus_dbus_file_operations_complete_empty_trash() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-empty-trash",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NautilusDBusFileOperationsIface, handle_empty_trash),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * NautilusDBusFileOperations::handle-copy-file:
   * @object: A #NautilusDBusFileOperations.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_SourceFileURI: Argument passed by remote caller.
   * @arg_SourceDisplayName: Argument passed by remote caller.
   * @arg_DestinationDirectoryURI: Argument passed by remote caller.
   * @arg_DestinationDisplayName: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-apps-Nautilus-FileOperations.CopyFile">CopyFile()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call nautilus_dbus_file_operations_complete_copy_file() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-copy-file",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (NautilusDBusFileOperationsIface, handle_copy_file),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    5,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);

}

typedef NautilusDBusFileOperationsIface NautilusDBusFileOperationsInterface;
G_DEFINE_INTERFACE (NautilusDBusFileOperations, nautilus_dbus_file_operations, G_TYPE_OBJECT);

/**
 * nautilus_dbus_file_operations_call_copy_uris:
 * @proxy: A #NautilusDBusFileOperationsProxy.
 * @arg_SourceFilesURIList: Argument to pass with the method invocation.
 * @arg_DestinationDirectoryURI: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-apps-Nautilus-FileOperations.CopyURIs">CopyURIs()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call nautilus_dbus_file_operations_call_copy_uris_finish() to get the result of the operation.
 *
 * See nautilus_dbus_file_operations_call_copy_uris_sync() for the synchronous, blocking version of this method.
 */
void
nautilus_dbus_file_operations_call_copy_uris (
    NautilusDBusFileOperations *proxy,
    const gchar *const *arg_SourceFilesURIList,
    const gchar *arg_DestinationDirectoryURI,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "CopyURIs",
    g_variant_new ("(^ass)",
                   arg_SourceFilesURIList,
                   arg_DestinationDirectoryURI),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nautilus_dbus_file_operations_call_copy_uris_finish:
 * @proxy: A #NautilusDBusFileOperationsProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nautilus_dbus_file_operations_call_copy_uris().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nautilus_dbus_file_operations_call_copy_uris().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nautilus_dbus_file_operations_call_copy_uris_finish (
    NautilusDBusFileOperations *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nautilus_dbus_file_operations_call_copy_uris_sync:
 * @proxy: A #NautilusDBusFileOperationsProxy.
 * @arg_SourceFilesURIList: Argument to pass with the method invocation.
 * @arg_DestinationDirectoryURI: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-apps-Nautilus-FileOperations.CopyURIs">CopyURIs()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nautilus_dbus_file_operations_call_copy_uris() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nautilus_dbus_file_operations_call_copy_uris_sync (
    NautilusDBusFileOperations *proxy,
    const gchar *const *arg_SourceFilesURIList,
    const gchar *arg_DestinationDirectoryURI,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "CopyURIs",
    g_variant_new ("(^ass)",
                   arg_SourceFilesURIList,
                   arg_DestinationDirectoryURI),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nautilus_dbus_file_operations_call_empty_trash:
 * @proxy: A #NautilusDBusFileOperationsProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-apps-Nautilus-FileOperations.EmptyTrash">EmptyTrash()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call nautilus_dbus_file_operations_call_empty_trash_finish() to get the result of the operation.
 *
 * See nautilus_dbus_file_operations_call_empty_trash_sync() for the synchronous, blocking version of this method.
 */
void
nautilus_dbus_file_operations_call_empty_trash (
    NautilusDBusFileOperations *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "EmptyTrash",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nautilus_dbus_file_operations_call_empty_trash_finish:
 * @proxy: A #NautilusDBusFileOperationsProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nautilus_dbus_file_operations_call_empty_trash().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nautilus_dbus_file_operations_call_empty_trash().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nautilus_dbus_file_operations_call_empty_trash_finish (
    NautilusDBusFileOperations *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nautilus_dbus_file_operations_call_empty_trash_sync:
 * @proxy: A #NautilusDBusFileOperationsProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-apps-Nautilus-FileOperations.EmptyTrash">EmptyTrash()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nautilus_dbus_file_operations_call_empty_trash() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nautilus_dbus_file_operations_call_empty_trash_sync (
    NautilusDBusFileOperations *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "EmptyTrash",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nautilus_dbus_file_operations_call_copy_file:
 * @proxy: A #NautilusDBusFileOperationsProxy.
 * @arg_SourceFileURI: Argument to pass with the method invocation.
 * @arg_SourceDisplayName: Argument to pass with the method invocation.
 * @arg_DestinationDirectoryURI: Argument to pass with the method invocation.
 * @arg_DestinationDisplayName: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-apps-Nautilus-FileOperations.CopyFile">CopyFile()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call nautilus_dbus_file_operations_call_copy_file_finish() to get the result of the operation.
 *
 * See nautilus_dbus_file_operations_call_copy_file_sync() for the synchronous, blocking version of this method.
 */
void
nautilus_dbus_file_operations_call_copy_file (
    NautilusDBusFileOperations *proxy,
    const gchar *arg_SourceFileURI,
    const gchar *arg_SourceDisplayName,
    const gchar *arg_DestinationDirectoryURI,
    const gchar *arg_DestinationDisplayName,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "CopyFile",
    g_variant_new ("(ssss)",
                   arg_SourceFileURI,
                   arg_SourceDisplayName,
                   arg_DestinationDirectoryURI,
                   arg_DestinationDisplayName),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * nautilus_dbus_file_operations_call_copy_file_finish:
 * @proxy: A #NautilusDBusFileOperationsProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nautilus_dbus_file_operations_call_copy_file().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with nautilus_dbus_file_operations_call_copy_file().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nautilus_dbus_file_operations_call_copy_file_finish (
    NautilusDBusFileOperations *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nautilus_dbus_file_operations_call_copy_file_sync:
 * @proxy: A #NautilusDBusFileOperationsProxy.
 * @arg_SourceFileURI: Argument to pass with the method invocation.
 * @arg_SourceDisplayName: Argument to pass with the method invocation.
 * @arg_DestinationDirectoryURI: Argument to pass with the method invocation.
 * @arg_DestinationDisplayName: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-apps-Nautilus-FileOperations.CopyFile">CopyFile()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See nautilus_dbus_file_operations_call_copy_file() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
nautilus_dbus_file_operations_call_copy_file_sync (
    NautilusDBusFileOperations *proxy,
    const gchar *arg_SourceFileURI,
    const gchar *arg_SourceDisplayName,
    const gchar *arg_DestinationDirectoryURI,
    const gchar *arg_DestinationDisplayName,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "CopyFile",
    g_variant_new ("(ssss)",
                   arg_SourceFileURI,
                   arg_SourceDisplayName,
                   arg_DestinationDirectoryURI,
                   arg_DestinationDisplayName),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * nautilus_dbus_file_operations_complete_copy_uris:
 * @object: A #NautilusDBusFileOperations.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-apps-Nautilus-FileOperations.CopyURIs">CopyURIs()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nautilus_dbus_file_operations_complete_copy_uris (
    NautilusDBusFileOperations *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * nautilus_dbus_file_operations_complete_empty_trash:
 * @object: A #NautilusDBusFileOperations.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-apps-Nautilus-FileOperations.EmptyTrash">EmptyTrash()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nautilus_dbus_file_operations_complete_empty_trash (
    NautilusDBusFileOperations *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * nautilus_dbus_file_operations_complete_copy_file:
 * @object: A #NautilusDBusFileOperations.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-apps-Nautilus-FileOperations.CopyFile">CopyFile()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
nautilus_dbus_file_operations_complete_copy_file (
    NautilusDBusFileOperations *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * NautilusDBusFileOperationsProxy:
 *
 * The #NautilusDBusFileOperationsProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NautilusDBusFileOperationsProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NautilusDBusFileOperationsProxy.
 */

struct _NautilusDBusFileOperationsProxyPrivate
{
  GData *qdata;
};

static void nautilus_dbus_file_operations_proxy_iface_init (NautilusDBusFileOperationsIface *iface);

G_DEFINE_TYPE_WITH_CODE (NautilusDBusFileOperationsProxy, nautilus_dbus_file_operations_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (NAUTILUS_DBUS_TYPE_FILE_OPERATIONS, nautilus_dbus_file_operations_proxy_iface_init));

static void
nautilus_dbus_file_operations_proxy_finalize (GObject *object)
{
  NautilusDBusFileOperationsProxy *proxy = NAUTILUS_DBUS_FILE_OPERATIONS_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (nautilus_dbus_file_operations_proxy_parent_class)->finalize (object);
}

static void
nautilus_dbus_file_operations_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
nautilus_dbus_file_operations_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
nautilus_dbus_file_operations_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_nautilus_dbus_file_operations_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], NAUTILUS_DBUS_TYPE_FILE_OPERATIONS);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, NAUTILUS_DBUS_TYPE_FILE_OPERATIONS);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
nautilus_dbus_file_operations_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  NautilusDBusFileOperationsProxy *proxy = NAUTILUS_DBUS_FILE_OPERATIONS_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nautilus_dbus_file_operations_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nautilus_dbus_file_operations_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
nautilus_dbus_file_operations_proxy_init (NautilusDBusFileOperationsProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, NAUTILUS_DBUS_TYPE_FILE_OPERATIONS_PROXY, NautilusDBusFileOperationsProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), nautilus_dbus_file_operations_interface_info ());
}

static void
nautilus_dbus_file_operations_proxy_class_init (NautilusDBusFileOperationsProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (NautilusDBusFileOperationsProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = nautilus_dbus_file_operations_proxy_finalize;
  gobject_class->get_property = nautilus_dbus_file_operations_proxy_get_property;
  gobject_class->set_property = nautilus_dbus_file_operations_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = nautilus_dbus_file_operations_proxy_g_signal;
  proxy_class->g_properties_changed = nautilus_dbus_file_operations_proxy_g_properties_changed;

}

static void
nautilus_dbus_file_operations_proxy_iface_init (NautilusDBusFileOperationsIface *iface)
{
}

/**
 * nautilus_dbus_file_operations_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-apps-Nautilus-FileOperations.top_of_page">apps.Nautilus.FileOperations</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call nautilus_dbus_file_operations_proxy_new_finish() to get the result of the operation.
 *
 * See nautilus_dbus_file_operations_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
nautilus_dbus_file_operations_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (NAUTILUS_DBUS_TYPE_FILE_OPERATIONS_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "apps.Nautilus.FileOperations", NULL);
}

/**
 * nautilus_dbus_file_operations_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nautilus_dbus_file_operations_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nautilus_dbus_file_operations_proxy_new().
 *
 * Returns: (transfer full) (type NautilusDBusFileOperationsProxy): The constructed proxy object or %NULL if @error is set.
 */
NautilusDBusFileOperations *
nautilus_dbus_file_operations_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return NAUTILUS_DBUS_FILE_OPERATIONS (ret);
  else
    return NULL;
}

/**
 * nautilus_dbus_file_operations_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-apps-Nautilus-FileOperations.top_of_page">apps.Nautilus.FileOperations</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nautilus_dbus_file_operations_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NautilusDBusFileOperationsProxy): The constructed proxy object or %NULL if @error is set.
 */
NautilusDBusFileOperations *
nautilus_dbus_file_operations_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (NAUTILUS_DBUS_TYPE_FILE_OPERATIONS_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "apps.Nautilus.FileOperations", NULL);
  if (ret != NULL)
    return NAUTILUS_DBUS_FILE_OPERATIONS (ret);
  else
    return NULL;
}


/**
 * nautilus_dbus_file_operations_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like nautilus_dbus_file_operations_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call nautilus_dbus_file_operations_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See nautilus_dbus_file_operations_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
nautilus_dbus_file_operations_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (NAUTILUS_DBUS_TYPE_FILE_OPERATIONS_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "apps.Nautilus.FileOperations", NULL);
}

/**
 * nautilus_dbus_file_operations_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nautilus_dbus_file_operations_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nautilus_dbus_file_operations_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type NautilusDBusFileOperationsProxy): The constructed proxy object or %NULL if @error is set.
 */
NautilusDBusFileOperations *
nautilus_dbus_file_operations_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return NAUTILUS_DBUS_FILE_OPERATIONS (ret);
  else
    return NULL;
}

/**
 * nautilus_dbus_file_operations_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like nautilus_dbus_file_operations_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nautilus_dbus_file_operations_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NautilusDBusFileOperationsProxy): The constructed proxy object or %NULL if @error is set.
 */
NautilusDBusFileOperations *
nautilus_dbus_file_operations_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (NAUTILUS_DBUS_TYPE_FILE_OPERATIONS_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "apps.Nautilus.FileOperations", NULL);
  if (ret != NULL)
    return NAUTILUS_DBUS_FILE_OPERATIONS (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * NautilusDBusFileOperationsSkeleton:
 *
 * The #NautilusDBusFileOperationsSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NautilusDBusFileOperationsSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NautilusDBusFileOperationsSkeleton.
 */

struct _NautilusDBusFileOperationsSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_nautilus_dbus_file_operations_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  NautilusDBusFileOperationsSkeleton *skeleton = NAUTILUS_DBUS_FILE_OPERATIONS_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], NAUTILUS_DBUS_TYPE_FILE_OPERATIONS);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, NAUTILUS_DBUS_TYPE_FILE_OPERATIONS);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_nautilus_dbus_file_operations_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  NautilusDBusFileOperationsSkeleton *skeleton = NAUTILUS_DBUS_FILE_OPERATIONS_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nautilus_dbus_file_operations_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_nautilus_dbus_file_operations_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  NautilusDBusFileOperationsSkeleton *skeleton = NAUTILUS_DBUS_FILE_OPERATIONS_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_nautilus_dbus_file_operations_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _nautilus_dbus_file_operations_skeleton_vtable =
{
  _nautilus_dbus_file_operations_skeleton_handle_method_call,
  _nautilus_dbus_file_operations_skeleton_handle_get_property,
  _nautilus_dbus_file_operations_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
nautilus_dbus_file_operations_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return nautilus_dbus_file_operations_interface_info ();
}

static GDBusInterfaceVTable *
nautilus_dbus_file_operations_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_nautilus_dbus_file_operations_skeleton_vtable;
}

static GVariant *
nautilus_dbus_file_operations_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  NautilusDBusFileOperationsSkeleton *skeleton = NAUTILUS_DBUS_FILE_OPERATIONS_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_nautilus_dbus_file_operations_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _nautilus_dbus_file_operations_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _nautilus_dbus_file_operations_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _nautilus_dbus_file_operations_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "apps.Nautilus.FileOperations", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
nautilus_dbus_file_operations_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void nautilus_dbus_file_operations_skeleton_iface_init (NautilusDBusFileOperationsIface *iface);
G_DEFINE_TYPE_WITH_CODE (NautilusDBusFileOperationsSkeleton, nautilus_dbus_file_operations_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (NAUTILUS_DBUS_TYPE_FILE_OPERATIONS, nautilus_dbus_file_operations_skeleton_iface_init));

static void
nautilus_dbus_file_operations_skeleton_finalize (GObject *object)
{
  NautilusDBusFileOperationsSkeleton *skeleton = NAUTILUS_DBUS_FILE_OPERATIONS_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (nautilus_dbus_file_operations_skeleton_parent_class)->finalize (object);
}

static void
nautilus_dbus_file_operations_skeleton_init (NautilusDBusFileOperationsSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, NAUTILUS_DBUS_TYPE_FILE_OPERATIONS_SKELETON, NautilusDBusFileOperationsSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
nautilus_dbus_file_operations_skeleton_class_init (NautilusDBusFileOperationsSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (NautilusDBusFileOperationsSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = nautilus_dbus_file_operations_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = nautilus_dbus_file_operations_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = nautilus_dbus_file_operations_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = nautilus_dbus_file_operations_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = nautilus_dbus_file_operations_skeleton_dbus_interface_get_vtable;
}

static void
nautilus_dbus_file_operations_skeleton_iface_init (NautilusDBusFileOperationsIface *iface)
{
}

/**
 * nautilus_dbus_file_operations_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-apps-Nautilus-FileOperations.top_of_page">apps.Nautilus.FileOperations</link>.
 *
 * Returns: (transfer full) (type NautilusDBusFileOperationsSkeleton): The skeleton object.
 */
NautilusDBusFileOperations *
nautilus_dbus_file_operations_skeleton_new (void)
{
  return NAUTILUS_DBUS_FILE_OPERATIONS (g_object_new (NAUTILUS_DBUS_TYPE_FILE_OPERATIONS_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for Object, ObjectProxy and ObjectSkeleton
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:NautilusDBusObject
 * @title: NautilusDBusObject
 * @short_description: Specialized GDBusObject types
 *
 * This section contains the #NautilusDBusObject, #NautilusDBusObjectProxy, and #NautilusDBusObjectSkeleton types which make it easier to work with objects implementing generated types for D-Bus interfaces.
 */

/**
 * NautilusDBusObject:
 *
 * The #NautilusDBusObject type is a specialized container of interfaces.
 */

/**
 * NautilusDBusObjectIface:
 * @parent_iface: The parent interface.
 *
 * Virtual table for the #NautilusDBusObject interface.
 */

static void
nautilus_dbus_object_default_init (NautilusDBusObjectIface *iface)
{
  /**
   * NautilusDBusObject:file-operations:
   *
   * The #NautilusDBusFileOperations instance corresponding to the D-Bus interface <link linkend="gdbus-interface-apps-Nautilus-FileOperations.top_of_page">apps.Nautilus.FileOperations</link>, if any.
   *
   * Connect to the #GObject::notify signal to get informed of property changes.
   */
  g_object_interface_install_property (iface, g_param_spec_object ("file-operations", "file-operations", "file-operations", NAUTILUS_DBUS_TYPE_FILE_OPERATIONS, G_PARAM_READWRITE|G_PARAM_STATIC_STRINGS));

}

typedef NautilusDBusObjectIface NautilusDBusObjectInterface;
G_DEFINE_INTERFACE_WITH_CODE (NautilusDBusObject, nautilus_dbus_object, G_TYPE_OBJECT, g_type_interface_add_prerequisite (g_define_type_id, G_TYPE_DBUS_OBJECT));

/**
 * nautilus_dbus_object_get_file_operations:
 * @object: A #NautilusDBusObject.
 *
 * Gets the #NautilusDBusFileOperations instance for the D-Bus interface <link linkend="gdbus-interface-apps-Nautilus-FileOperations.top_of_page">apps.Nautilus.FileOperations</link> on @object, if any.
 *
 * Returns: (transfer full): A #NautilusDBusFileOperations that must be freed with g_object_unref() or %NULL if @object does not implement the interface.
 */
NautilusDBusFileOperations *nautilus_dbus_object_get_file_operations (NautilusDBusObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "apps.Nautilus.FileOperations");
  if (ret == NULL)
    return NULL;
  return NAUTILUS_DBUS_FILE_OPERATIONS (ret);
}


/**
 * nautilus_dbus_object_peek_file_operations: (skip)
 * @object: A #NautilusDBusObject.
 *
 * Like nautilus_dbus_object_get_file_operations() but doesn't increase the reference count on the returned object.
 *
 * <warning>It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.</warning>
 *
 * Returns: (transfer none): A #NautilusDBusFileOperations or %NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
 */
NautilusDBusFileOperations *nautilus_dbus_object_peek_file_operations (NautilusDBusObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "apps.Nautilus.FileOperations");
  if (ret == NULL)
    return NULL;
  g_object_unref (ret);
  return NAUTILUS_DBUS_FILE_OPERATIONS (ret);
}


static void
nautilus_dbus_object_notify (GDBusObject *object, GDBusInterface *interface)
{
  g_object_notify (G_OBJECT (object), ((_ExtendedGDBusInterfaceInfo *) g_dbus_interface_get_info (interface))->hyphen_name);
}

/**
 * NautilusDBusObjectProxy:
 *
 * The #NautilusDBusObjectProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NautilusDBusObjectProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NautilusDBusObjectProxy.
 */

static void
nautilus_dbus_object_proxy__nautilus_dbus_object_iface_init (NautilusDBusObjectIface *iface)
{
}

static void
nautilus_dbus_object_proxy__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = nautilus_dbus_object_notify;
  iface->interface_removed = nautilus_dbus_object_notify;
}


G_DEFINE_TYPE_WITH_CODE (NautilusDBusObjectProxy, nautilus_dbus_object_proxy, G_TYPE_DBUS_OBJECT_PROXY,
                         G_IMPLEMENT_INTERFACE (NAUTILUS_DBUS_TYPE_OBJECT, nautilus_dbus_object_proxy__nautilus_dbus_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, nautilus_dbus_object_proxy__g_dbus_object_iface_init));

static void
nautilus_dbus_object_proxy_init (NautilusDBusObjectProxy *object)
{
}

static void
nautilus_dbus_object_proxy_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
}

static void
nautilus_dbus_object_proxy_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  NautilusDBusObjectProxy *object = NAUTILUS_DBUS_OBJECT_PROXY (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "apps.Nautilus.FileOperations");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
nautilus_dbus_object_proxy_class_init (NautilusDBusObjectProxyClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = nautilus_dbus_object_proxy_set_property;
  gobject_class->get_property = nautilus_dbus_object_proxy_get_property;

  g_object_class_override_property (gobject_class, 1, "file-operations");
}

/**
 * nautilus_dbus_object_proxy_new:
 * @connection: A #GDBusConnection.
 * @object_path: An object path.
 *
 * Creates a new proxy object.
 *
 * Returns: (transfer full): The proxy object.
 */
NautilusDBusObjectProxy *
nautilus_dbus_object_proxy_new (GDBusConnection *connection,
  const gchar *object_path)
{
  g_return_val_if_fail (G_IS_DBUS_CONNECTION (connection), NULL);
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return NAUTILUS_DBUS_OBJECT_PROXY (g_object_new (NAUTILUS_DBUS_TYPE_OBJECT_PROXY, "g-connection", connection, "g-object-path", object_path, NULL));
}

/**
 * NautilusDBusObjectSkeleton:
 *
 * The #NautilusDBusObjectSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NautilusDBusObjectSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NautilusDBusObjectSkeleton.
 */

static void
nautilus_dbus_object_skeleton__nautilus_dbus_object_iface_init (NautilusDBusObjectIface *iface)
{
}


static void
nautilus_dbus_object_skeleton__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = nautilus_dbus_object_notify;
  iface->interface_removed = nautilus_dbus_object_notify;
}

G_DEFINE_TYPE_WITH_CODE (NautilusDBusObjectSkeleton, nautilus_dbus_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON,
                         G_IMPLEMENT_INTERFACE (NAUTILUS_DBUS_TYPE_OBJECT, nautilus_dbus_object_skeleton__nautilus_dbus_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, nautilus_dbus_object_skeleton__g_dbus_object_iface_init));

static void
nautilus_dbus_object_skeleton_init (NautilusDBusObjectSkeleton *object)
{
}

static void
nautilus_dbus_object_skeleton_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  NautilusDBusObjectSkeleton *object = NAUTILUS_DBUS_OBJECT_SKELETON (gobject);
  GDBusInterfaceSkeleton *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_value_get_object (value);
      if (interface != NULL)
        {
          g_warn_if_fail (NAUTILUS_DBUS_IS_FILE_OPERATIONS (interface));
          g_dbus_object_skeleton_add_interface (G_DBUS_OBJECT_SKELETON (object), interface);
        }
      else
        {
          g_dbus_object_skeleton_remove_interface_by_name (G_DBUS_OBJECT_SKELETON (object), "apps.Nautilus.FileOperations");
        }
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
nautilus_dbus_object_skeleton_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  NautilusDBusObjectSkeleton *object = NAUTILUS_DBUS_OBJECT_SKELETON (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "apps.Nautilus.FileOperations");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
nautilus_dbus_object_skeleton_class_init (NautilusDBusObjectSkeletonClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = nautilus_dbus_object_skeleton_set_property;
  gobject_class->get_property = nautilus_dbus_object_skeleton_get_property;

  g_object_class_override_property (gobject_class, 1, "file-operations");
}

/**
 * nautilus_dbus_object_skeleton_new:
 * @object_path: An object path.
 *
 * Creates a new skeleton object.
 *
 * Returns: (transfer full): The skeleton object.
 */
NautilusDBusObjectSkeleton *
nautilus_dbus_object_skeleton_new (const gchar *object_path)
{
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return NAUTILUS_DBUS_OBJECT_SKELETON (g_object_new (NAUTILUS_DBUS_TYPE_OBJECT_SKELETON, "g-object-path", object_path, NULL));
}

/**
 * nautilus_dbus_object_skeleton_set_file_operations:
 * @object: A #NautilusDBusObjectSkeleton.
 * @interface_: (allow-none): A #NautilusDBusFileOperations or %NULL to clear the interface.
 *
 * Sets the #NautilusDBusFileOperations instance for the D-Bus interface <link linkend="gdbus-interface-apps-Nautilus-FileOperations.top_of_page">apps.Nautilus.FileOperations</link> on @object.
 */
void nautilus_dbus_object_skeleton_set_file_operations (NautilusDBusObjectSkeleton *object, NautilusDBusFileOperations *interface_)
{
  g_object_set (G_OBJECT (object), "file-operations", interface_, NULL);
}


/* ------------------------------------------------------------------------
 * Code for ObjectManager client
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:NautilusDBusObjectManagerClient
 * @title: NautilusDBusObjectManagerClient
 * @short_description: Generated GDBusObjectManagerClient type
 *
 * This section contains a #GDBusObjectManagerClient that uses nautilus_dbus_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc.
 */

/**
 * NautilusDBusObjectManagerClient:
 *
 * The #NautilusDBusObjectManagerClient structure contains only private data and should only be accessed using the provided API.
 */

/**
 * NautilusDBusObjectManagerClientClass:
 * @parent_class: The parent class.
 *
 * Class structure for #NautilusDBusObjectManagerClient.
 */

G_DEFINE_TYPE (NautilusDBusObjectManagerClient, nautilus_dbus_object_manager_client, G_TYPE_DBUS_OBJECT_MANAGER_CLIENT);

static void
nautilus_dbus_object_manager_client_init (NautilusDBusObjectManagerClient *manager)
{
}

static void
nautilus_dbus_object_manager_client_class_init (NautilusDBusObjectManagerClientClass *klass)
{
}

/**
 * nautilus_dbus_object_manager_client_get_proxy_type:
 * @manager: A #GDBusObjectManagerClient.
 * @object_path: The object path of the remote object (unused).
 * @interface_name: (allow-none): Interface name of the remote object or %NULL to get the object proxy #GType.
 * @user_data: User data (unused).
 *
 * A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy<!-- -->- and #GDBusProxy<!-- -->-derived types.
 *
 * Returns: A #GDBusProxy<!-- -->-derived #GType if @interface_name is not %NULL, otherwise the #GType for #NautilusDBusObjectProxy.
 */
GType
nautilus_dbus_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data)
{
  static gsize once_init_value = 0;
  static GHashTable *lookup_hash;
  GType ret;

  if (interface_name == NULL)
    return NAUTILUS_DBUS_TYPE_OBJECT_PROXY;
  if (g_once_init_enter (&once_init_value))
    {
      lookup_hash = g_hash_table_new (g_str_hash, g_str_equal);
      g_hash_table_insert (lookup_hash, "apps.Nautilus.FileOperations", GSIZE_TO_POINTER (NAUTILUS_DBUS_TYPE_FILE_OPERATIONS_PROXY));
      g_once_init_leave (&once_init_value, 1);
    }
  ret = (GType) GPOINTER_TO_SIZE (g_hash_table_lookup (lookup_hash, interface_name));
  if (ret == (GType) 0)
    ret = G_TYPE_DBUS_PROXY;
  return ret;
}

/**
 * nautilus_dbus_object_manager_client_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates #GDBusObjectManagerClient using nautilus_dbus_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call nautilus_dbus_object_manager_client_new_finish() to get the result of the operation.
 *
 * See nautilus_dbus_object_manager_client_new_sync() for the synchronous, blocking version of this constructor.
 */
void
nautilus_dbus_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (NAUTILUS_DBUS_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", nautilus_dbus_object_manager_client_get_proxy_type, NULL);
}

/**
 * nautilus_dbus_object_manager_client_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nautilus_dbus_object_manager_client_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nautilus_dbus_object_manager_client_new().
 *
 * Returns: (transfer full) (type NautilusDBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
nautilus_dbus_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * nautilus_dbus_object_manager_client_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates #GDBusObjectManagerClient using nautilus_dbus_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nautilus_dbus_object_manager_client_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NautilusDBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
nautilus_dbus_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (NAUTILUS_DBUS_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", nautilus_dbus_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


/**
 * nautilus_dbus_object_manager_client_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like nautilus_dbus_object_manager_client_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call nautilus_dbus_object_manager_client_new_for_bus_finish() to get the result of the operation.
 *
 * See nautilus_dbus_object_manager_client_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
nautilus_dbus_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (NAUTILUS_DBUS_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", nautilus_dbus_object_manager_client_get_proxy_type, NULL);
}

/**
 * nautilus_dbus_object_manager_client_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to nautilus_dbus_object_manager_client_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with nautilus_dbus_object_manager_client_new_for_bus().
 *
 * Returns: (transfer full) (type NautilusDBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
nautilus_dbus_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * nautilus_dbus_object_manager_client_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like nautilus_dbus_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See nautilus_dbus_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type NautilusDBusObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
nautilus_dbus_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (NAUTILUS_DBUS_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", nautilus_dbus_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


